frontend:
  issuer: kedro-graphql
issuer: http://localhost:5556/oidc
enablePasswordDB: true
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: localhost:5556
oauth2:
  skipApprovalScreen: true
staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
staticClients:
  - id: kedro-graphql
    name: 'kedro-graphql'
    secret: 'kedro-graphql'
    redirectURIs:
      - 'http://localhost:4180/oauth2/callback'

