# mkdocs.yml
site_name: Kedro GraphQL
site_url: https://cellsignal.github.io/kedro-graphql/
repo_url: https://github.com/cellsignal/kedro-graphql
extra:
  version:
    provider: mike
theme:
  name: "material"
  features:
  - navigation.expand
  - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Configuration: configuration.md
  - Events: events.md
  - UI: ui.md
  - Extend Kedro GraphQL:
      - GraphQL: extend_graphql.md
      - Dataset Uploads & Downloads: extend_signed_url_provider.md
      - Authentication & Authorization: extend_permissions.md
      - Application: extend_application.md
  - Architecture: architecture.md
  - Reference: pydoc.md
